toyota <- read.csv(file.choose()) # choose the Cars.csv data set
View(toyota)
toyota1 <- toyota[c("Price","Age_08_04","KM","HP","cc","Doors","Gears","Quarterly_Tax","Weight")]
View(toyota1)
attach(toyota1)
#EDA
a <- mean(Price)
b <- mean(Age_08_04)
c <- mean(KM)
d <- mean(HP)
e <- mean(cc)
f <- mean(Doors)
g <- mean(Gears)
h <- mean(Quarterly_Tax)
i <- mean(Weight)
m1 <- median(Price)
m2 <- median(Age_08_04)
m3 <- median(KM)
m4 <- median(HP)
m5 <- median(cc)
m6 <- median(Doors)
m7 <- median(Gears)
m8 <- median(Quarterly_Tax)
m9 <- median(Weight)
mo1 <- 3*m1 - 2*a
mo2 <- 3*m2 - 2*b
mo3 <- 3*m3 - 2*c
mo4 <- 3*m4 - 2*d
mo5 <- 3*m5 - 2*e
mo6 <- 3*m6 - 2*f
mo7 <- 3*m7 - 2*g
mo8 <- 3*m8 - 2*h
mo9 <- 3*m9 - 2*i
sd(Price)
sd(Age_08_04)
sd(KM)
sd(HP)
sd(cc)
sd(Doors)
sd(Gears)
sd(Quarterly_Tax)
sd(Weight)   
var(Price)
var(Age_08_04)
var(KM)
var(HP)
var(cc)
var(Doors)
var(Gears)
var(Quarterly_Tax)
var(Weight)
library(moments)
skewness(Price)
skewness(Age_08_04)
skewness(KM)
skewness(HP)
skewness(cc)
skewness(Doors)
skewness(Gears)
skewness(Quarterly_Tax)
skewness(Weight)
kurtosis(Price)
kurtosis(Age_08_04)
kurtosis(KM)
kurtosis(HP)
kurtosis(cc)
kurtosis(Doors)
kurtosis(Gears)
kurtosis(Quarterly_Tax)
kurtosis(Weight)
plot(toyota1)
cor(toyota1)
summary(toyota1)
pairs(toyota1)
cor(toyota1)
install.packages("corpcor")
library(corpcor)
cor2pcor(cor(toyota1))
model.Toyota1 <- lm(Price ~.,data=toyota1)
summary(model.Toyota1)
influence.measures(model.Toyota1)
library(car)
windows()
influenceIndexPlot(model.Toyota1,id.n=3) 
influencePlot(model.Toyota1,id.n=3) 
model.toyo2<-lm(Price~Age_08_04+KM+HP+cc+Gears+Doors+Weight+Quarterly_Tax,data = toyota1[-81,])
summary(model.toyo2)
vif(corolla.price1)
plot(Age_08_04,KM, col="dodgerblue4",pch=20)
avPlots(model.toyo2,id.n=2,id.cex=0.7)
finalmodel <- lm(Price ~ Age_08_04+KM+HP+cc+Gears+Doors+Weight+Quarterly_Tax)
summary(finalmodel)
plot(model.Toyota1)

